language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_script: cd henrique-andrade-dev/decode-mips

script:
  - cd src
  - javac *.java
  - jar cvfm ../decode-mips.jar Manifest.mf *.class
